# Generated by Django 4.0.4 on 2022-06-22 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.CharField(max_length=150)),
                ('display', models.ImageField(default='post-3.jpg', upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='servicestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('experience', models.IntegerField()),
                ('no_of_awards', models.IntegerField()),
                ('no_of_works_completed', models.IntegerField()),
                ('clients_dealed', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('dp', models.ImageField(default='avatar.svg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=150)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('service1', models.CharField(max_length=100)),
                ('description1', models.TextField(blank=True)),
                ('service2', models.CharField(max_length=100)),
                ('description2', models.TextField(blank=True)),
                ('service3', models.CharField(max_length=100)),
                ('description3', models.TextField(blank=True)),
                ('service4', models.CharField(max_length=100)),
                ('description4', models.TextField(blank=True)),
                ('service5', models.CharField(max_length=100)),
                ('description5', models.TextField(blank=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='coding_languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=150)),
                ('percentage_contributed', models.IntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
