# Generated by Django 4.0.4 on 2022-06-22 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mail', models.EmailField(max_length=254)),
                ('comment', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='service1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='service2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='service3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='service4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='service5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_name', models.CharField(max_length=100)),
                ('reply_created', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comment')),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('pic', models.ImageField(upload_to='')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
