# Generated by Django 4.0.4 on 2022-06-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment_alter_services_service1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.CharField(default='my reply', max_length=300),
        ),
    ]
