# Generated by Django 4.0.4 on 2022-06-22 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment_blog_alter_blog_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='commentor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.blog'),
        ),
    ]
