# Generated by Django 4.0.4 on 2022-06-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reply_commentor_alter_blog_host_alter_comment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dp',
            field=models.ImageField(default='avatar.svg', upload_to=''),
        ),
        migrations.AddField(
            model_name='reply',
            name='dpic',
            field=models.ImageField(default='avatar.svg', upload_to=''),
        ),
    ]
