# Generated by Django 4.0.4 on 2022-06-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_comment_dp_reply_dpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='dpic',
            field=models.ImageField(default='emoji.webp', upload_to=''),
        ),
    ]
