# Generated by Django 4.0.4 on 2022-06-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_projects_alter_reply_dpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='title',
        ),
    ]
