# Generated by Django 4.0.4 on 2022-06-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_projects_img1_alter_projects_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projects',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
