# Generated by Django 4.0.4 on 2022-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_projects_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hero_bg',
            field=models.ImageField(default='hero-bg.jpg', upload_to=''),
        ),
    ]
