# Generated by Django 4.0.4 on 2022-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_user_hero_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill3',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill4',
            field=models.CharField(default='', max_length=150),
        ),
    ]
